### ISSUE TITLE
Link to Note that does not yet exist

### ISSUE THREAD

**Issue by eikeon** [idkclub/Markology#14]
It'd be great if there was a way to link to a note that does not yet exist; where the link and note would both be created.

Loving the clean, simple, and solid app so far. Thank you.

**Comment by eikeon** [comment]
I see this functionality exists if I select text before clicking on `Add Link`

**Comment by arkie** [comment]
Just as a note, it should also be possible to type the title into the search bar and get the same behavior - let me know if that isn't working!

**Comment by eikeon** [comment]
Wonder if there's a UI hint to make the search bar option more clear?

**Comment by arkie** [comment]
Something like `Search or Create`? Definitely open to suggestions that would increase discoverability heh

**Comment by eikeon** [comment]
Might just be me too. Pretty clear already if I would have just started typing ;)

**Comment by eikeon** [comment]
But yeah, maybe just having `Search or Create` or some such... as there's room for it.

**Comment by eikeon** [comment]
Or have it like the main page where there's a place to type a new one... the New > Empty Note bit

**Comment by arkie** [comment]
(it's actually the same UI control as the menu - so the Search -> New text behavior should already be the same 👀)
